@startuml
left to right direction

actor "Personnel Médical" as Staff
actor "Médecin" as Med
actor "Infirmier(ère)" as Inf
actor "Moniteur de Signes Vitaux" as Moniteur
actor "Caméra OCR" as Camera
actor "Système de Notification" as Notif

Med --|> Staff
Inf --|> Staff

rectangle "Système de Surveillance Médicale" {

    usecase "Collecte des données \n depuis les moniteurs Mindray (API/HL7)" as UC1
    usecase "Collecte des données \n via caméra OCR" as UC2
    usecase "Reconnaissance des \n valeurs vitales (OCR)" as UC3
    usecase "Génération des alertes \n selon seuils" as UC4
    usecase "Visualisation des données \n patient (web/mobile)" as UC5
    usecase "Authentification et \n gestion des utilisateurs" as UC6
    usecase "Livraison des notifications \n (e-mail, push, SMS)" as UC7
    usecase "Stockage et historique \n des données médicales" as UC8
    usecase "Configuration des seuils d'alerte \n par patient ou bloc" as UC9

    Staff --> UC5
    Staff --> UC4
    Staff --> UC9

    Moniteur --> UC1
    Camera --> UC2
    UC1 --> UC3
    UC2 --> UC3
    UC3 --> UC4
    UC4 --> UC7
    UC7 --> Notif
    UC8 --> UC5
}

@enduml
