@startuml
title Diagramme d'activité

start

:Capture d'image par la caméra IP;
:Détection des zones d'intérêt (YOLO);
:Prétraitement d'image (OpenCV);
:Reconnaissance de texte (OCR Tesseract);
:Extraction des données vitales;

if (Données valides ?) then (oui)
  :Analyse des données;
  if (Anomalie détectée ?) then (oui)
    :Génération d'une alerte;
    :Envoi de l'alerte via FCM;
    :Affichage sur interfaces Web et Mobile;
  else (non)
    :Stockage des données dans la base MySQL;
  endif
else (non)
'   :Ignorer;
endif

stop
@enduml
