@startuml
title Diagramme de composants

skinparam component {
    BackgroundColor #E6E6FA
    BorderColor #4B0082
}

package "Backend" #87CEEB {
    component "Modules Python" #FFD700 {
        [OpenCV]
        [Tesseract OCR]
    }
    component "Services Laravel" #ADD8E6 {
        [Authentification]
        [Gestion des Alertes]
        [Notifications]
    }
    "Modules Python" --> "Services Laravel" : Données extraites
}

package "Frontend" #FFB6C1 {
    component "Tableaux de bord React" #DDA0DD {
        [Interface Visualisation]
    }
    component "Application Flutter" #98FB98 {
        [Interface Alertes Mobiles]
    }
    "Services Laravel" --> "Tableaux de bord React" : REST API / WebSocket
    "Services Laravel" --> "Application Flutter" : REST API / WebSocket
}

cloud "Firebase Cloud Messaging" #90EE90 {
    [Service de Notification]
}
"Services Laravel" --> "Firebase Cloud Messaging" : Alertes push
"Application Flutter" --> "Firebase Cloud Messaging" : Réception des notifications

@enduml