@startuml
title Flux de données

skinparam activity {
    BackgroundColor #E6E6FA
    BorderColor #4B0082
    FontColor #000000
}
skinparam note {
    BackgroundColor #FFFFFF
    BorderColor #4B0082
    FontColor #000000
}

start
:Collecte des données;


:Transmission au backend;


:Analyse et stockage;


:Détection des anomalies;

:Envoi d’alertes;

:Consultation par le personnel médical;

:Validation des actions;

stop

@enduml