@startuml

rectangle "Système VitalSync" {
    usecase "Authentifier" as Authenticate
    usecase "Consulter les données du patient" as ConsultPatientData
    usecase "Recevoir les alertes critiques" as ReceiveCriticalAlerts
}
actor "Médecin" as Doctor

Doctor --> Authenticate : Authentifier
Doctor --> ConsultPatientData : Consulter
Doctor --> ReceiveCriticalAlerts : Être notifié

@enduml
